version: "3"

silent: true

output: prefixed

tasks:
  release:
    - |
      git c
      # git tag -d v1.0 || true
      # git push origin --delete v1.0 || true
      # git tag v1.0
      # git push origin v1.0
