package main

import (
	"fmt"
	"os"
)

var version = "unknown - unofficial & generated by unknown"

func main() {
	root := flags()

	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
