name: gocry
on: [push, pull_request, workflow_dispatch]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  IMAGE: ${{ github.repository }}

jobs:
  # verify:
  #   uses: idelchi/devenv/.github/workflows/devenv-actions.yml@dev
  #   with:
  #     image: idelchi/devenv:dev

  release-docker:
    runs-on: ubuntu-24.04
    # needs: [verify]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  release-tag:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE }}:dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
