name: gocry

on:
  push:
    tags:
      - "*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: delete ${{github.ref_name}} release
        run: |
          echo ${{github.ref_name}}
          # git tag -d v0.0
          # git push origin --delete v0.0
        continue-on-error: true

      # - name: Set up Go
      #   uses: actions/setup-go@v5

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     distribution: goreleaser
      #     version: latest
      #     args: release --clean
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
