name: gocry

on:
  push:
    branches:
      - dev
      - master
    tags:
      - "*"

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/dev'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: delete v0.0 release
        run: |
          gh release delete v0.0 --yes --cleanup-tag || true
          git tag v1.0
          git push origin v1.0
        continue-on-error: true

  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
