name: gocry

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master
    tags:
      - "*"

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/dev'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: "v0.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: delete ${{ env.TAG }} release
        run: |
          gh release delete ${{ env.TAG }} --yes --cleanup-tag || true
        continue-on-error: true

      - name: delete ${{ env.TAG }} release
        run: |
          git tag -d ${{ env.TAG }}
          git push origin ${{ env.TAG }}

  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
